let nom = null;
let age = 0;
let ville = "";
let score = undefined;
let actif = false;
console.log("Partie A");
console.log("nom ?? \"valeur par défaut\"    -> " + (nom ?? "valeur par défaut"));
console.log("age ?? \"valeur par défaut\"    -> " + (age ?? "valeur par défaut"));
console.log("ville ?? \"valeur par défaut\"  -> " + (ville ?? "valeur par défaut"));
console.log("score ?? \"valeur par défaut\"  -> " + (score ?? "valeur par défaut"));
console.log("actif ?? \"valeur par défaut\"  -> " + (actif ?? "valeur par défaut"));
console.log("\nPartie B");
console.log("nom || \"valeur par défaut\"    -> " + (nom || "valeur par défaut"));
console.log("age || \"valeur par défaut\"    -> " + (age || "valeur par défaut"));
console.log("ville || \"valeur par défaut\"  -> " + (ville || "valeur par défaut"));
console.log("score || \"valeur par défaut\"  -> " + (score || "valeur par défaut"));
console.log("actif || \"valeur par défaut\"  -> " + (actif || "valeur par défaut"));
console.log("\nPartie C");
console.log("nom   : ?? et || -> " + ((nom ?? "def") === (nom || "def") ? "même résultat" : "résultat différent"));
console.log("age   : ?? et || -> " + ((age ?? "def") === (age || "def") ? "même résultat" : "résultat différent"));
console.log("ville : ?? et || -> " + ((ville ?? "def") === (ville || "def") ? "même résultat" : "résultat différent"));
console.log("score : ?? et || -> " + ((score ?? "def") === (score || "def") ? "même résultat" : "résultat différent"));
console.log("actif : ?? et || -> " + ((actif ?? "def") === (actif || "def") ? "même résultat" : "résultat différent"));